export type ProgressionAction = "increase_weight" | "increase_reps" | "keep_weight" | "reduce_load" | "deload";
export type EffortZone = "easy" | "productive" | "hard" | "failure";
export type ProgressionDecision = { action: ProgressionAction; confidence: number; recommendedWeight: number; recommendedReps: number; reason: string; signals: string[]; effortZone?: EffortZone; qualityScore?: number };
export type ProgressEngineInput = { weight:number; reps:number; minReps:number; maxReps:number; rir?:number|null; rpe?:number|null; readiness?:number|null; trendPercent?:number|null; recentMisses?:number; recentSessions?:number; techniqueGood?:boolean; fatigueTrend?:"improving"|"stable"|"rising"; consecutiveHardSets?:number };
export type LiveSetState = { setNumber:number; plannedSets:number; completedSets:number; weight:number; reps:number; rir:number; minReps:number; maxReps:number; readiness?:number|null; trendPercent?:number|null; recentMisses?:number; consecutiveHardSets?:number; baseRestSeconds?:number };
export type LiveSetDecision = ProgressionDecision & { nextSetNumber:number; shouldRest:boolean; suggestedRestSeconds:number };
function clamp(v:number,min:number,max:number){return Math.min(max,Math.max(min,v));}
export function getAdaptiveLoadIncrement(weight:number){if(weight<=0)return 0;if(weight<10)return 1;if(weight<20)return 2;return 2.5;}
export function estimateOneRepMax(weight:number,reps:number){return weight<=0||reps<=0?0:weight*(1+reps/30);}
export function normalizeRir(rir?:number|null,rpe?:number|null){if(typeof rir==="number"&&Number.isFinite(rir))return clamp(rir,0,5);if(typeof rpe==="number"&&Number.isFinite(rpe))return clamp(10-rpe,0,5);return null;}
export function getEffortZone(rir?:number|null,rpe?:number|null):EffortZone{const n=normalizeRir(rir,rpe);if(n===null)return "productive";if(n<=.5)return "failure";if(n<=2)return "hard";if(n<=4)return "productive";return "easy";}
export function getSuggestedRestSeconds(rir:number,baseRestSeconds:number,readiness?:number|null){const base=Math.max(30,baseRestSeconds);const effort=rir<=0?1.3:rir===1?1.2:rir===2?1.1:rir>=4?.9:1;const recovery=readiness!=null&&readiness<=2?1.15:1;return Math.round(base*effort*recovery/15)*15;}
export function getTrainingQualityScore(input:{completedSets:number;plannedSets:number;averageRir?:number|null;readiness?:number|null;trendPercent?:number|null;personalRecords?:number}){const completion=input.plannedSets>0?clamp(input.completedSets/input.plannedSets,0,1):0;const rir=input.averageRir==null?.7:1-clamp(Math.abs(input.averageRir-2.5)/4,0,1);const readiness=input.readiness==null?.7:clamp(input.readiness/5,0,1);const trend=input.trendPercent==null?.5:clamp(.5+input.trendPercent/20,0,1);const pr=Math.min(1,Math.max(0,input.personalRecords??0)/2);return Math.round(clamp(completion*35+rir*25+readiness*20+trend*15+pr*5,0,100));}

export function getProgressionDecision(input:ProgressEngineInput):ProgressionDecision{
 const weight=Math.max(0,input.weight), reps=Math.max(0,input.reps), minReps=Math.max(1,input.minReps), maxReps=Math.max(minReps,input.maxReps), rir=normalizeRir(input.rir,input.rpe), readiness=input.readiness??null, trend=input.trendPercent??0, misses=Math.max(0,input.recentMisses??0), sessions=Math.max(0,input.recentSessions??0), techniqueGood=input.techniqueGood!==false, hardSets=Math.max(0,input.consecutiveHardSets??0), fatigueRising=input.fatigueTrend==="rising";
 const signals:string[]=[]; const veryFatigued=readiness!==null&&readiness<=2; const ready=readiness!==null&&readiness>=4.2; const nearFailure=rir!==null&&rir<=1; const comfortable=rir!==null&&rir>=4; const strongTrend=trend>=3; const weakTrend=trend<=-3; const belowMinimum=reps<minReps; const effortZone=getEffortZone(input.rir,input.rpe);
 if(veryFatigued)signals.push("récupération basse"); if(ready)signals.push("récupération élevée"); if(nearFailure)signals.push("proche de l'échec"); if(comfortable)signals.push("marge importante"); if(strongTrend)signals.push("tendance de force positive"); if(weakTrend)signals.push("tendance de force négative"); if(belowMinimum)signals.push(`série écourtée à ${reps} reps`); if(misses>0)signals.push(`${misses} série(s) sous l'objectif récemment`); if(!techniqueGood)signals.push("technique à stabiliser"); if(fatigueRising)signals.push("fatigue en hausse"); if(hardSets>=2)signals.push("effort élevé sur plusieurs séries");
 const qualityScore=getTrainingQualityScore({completedSets:belowMinimum?.75:1,plannedSets:1,averageRir:rir,readiness,trendPercent:trend}); const increment=getAdaptiveLoadIncrement(weight);
 if(weight<=0)return {action:"keep_weight",confidence:.45,recommendedWeight:0,recommendedReps:minReps,reason:`Trouve d'abord une charge qui permet ${minReps}–${maxReps} reps propres.`,signals,effortZone,qualityScore};
 if(readiness!==null&&readiness<=1.5&&(fatigueRising||weakTrend))return {action:"deload",confidence:.93,recommendedWeight:Math.max(0,Number((weight*.85).toFixed(2))),recommendedReps:minReps,reason:"Récupération très basse et fatigue en hausse : une réduction temporaire protège la progression.",signals,effortZone,qualityScore};
 if(belowMinimum)return {action:"keep_weight",confidence:.94,recommendedWeight:weight,recommendedReps:minReps,reason:`Série écourtée à ${reps} reps. On garde ${weight} kg et on reconstruit les répétitions avant toute augmentation.`,signals,effortZone,qualityScore};
 if(!techniqueGood||veryFatigued||(nearFailure&&weakTrend))return {action:"keep_weight",confidence:.9,recommendedWeight:weight,recommendedReps:clamp(reps,minReps,maxReps),reason:!techniqueGood?"La technique doit rester la priorité avant toute surcharge.":"Les signaux de fatigue sont trop élevés pour augmenter la charge aujourd'hui.",signals,effortZone,qualityScore};
 if(misses>=2&&!ready)return {action:"reduce_load",confidence:.82,recommendedWeight:Math.max(0,weight-increment),recommendedReps:minReps,reason:"Les performances récentes montrent que la charge actuelle est trop ambitieuse. On réduit légèrement pour reconstruire une progression stable.",signals,effortZone,qualityScore};
 if(hardSets>=3&&readiness!==null&&readiness<4)return {action:"keep_weight",confidence:.89,recommendedWeight:weight,recommendedReps:minReps,reason:"Plusieurs séries sont déjà très exigeantes. On conserve la charge et on évite d'accumuler de la fatigue inutile.",signals,effortZone,qualityScore};
 if(reps>=maxReps&&(rir===null||rir>=2)&&techniqueGood&&!weakTrend){
   const allowedPercent=readiness===null?.025:readiness>=4.2?.05:readiness>=3.2?.025:0;
   if(allowedPercent<=0)return {action:"keep_weight",confidence:.9,recommendedWeight:weight,recommendedReps:minReps,reason:"La performance est bonne, mais ta récupération ne permet pas de surcharger aujourd'hui. Consolide cette charge.",signals:[...signals,"plafond de récupération actif"],effortZone,qualityScore};
   const target=Math.min(weight+increment,weight*(1+allowedPercent)); const rounded=Number((Math.round(target*2)/2).toFixed(2));
   return {action:"increase_weight",confidence:clamp(.78+(ready?.1:0)+(strongTrend?.07:0),.5,.97),recommendedWeight:Math.max(weight,rounded),recommendedReps:minReps,reason:`Haut de fourchette atteint avec suffisamment de marge. Progress+ autorise une hausse contrôlée jusqu'à ${Math.max(weight,rounded)} kg.`,signals,effortZone,qualityScore};
 }
 if(comfortable&&reps<maxReps)return {action:"increase_reps",confidence:.84,recommendedWeight:weight,recommendedReps:Math.min(maxReps,reps+1),reason:"Tu gardes beaucoup de marge. Ajoute une répétition avant d'augmenter la charge.",signals,effortZone,qualityScore};
 if(weakTrend&&sessions>=2)return {action:"keep_weight",confidence:.86,recommendedWeight:weight,recommendedReps:clamp(reps,minReps,maxReps),reason:"La tendance récente est en baisse. On consolide plutôt que de forcer une surcharge.",signals,effortZone,qualityScore};
 return {action:"increase_reps",confidence:.72,recommendedWeight:weight,recommendedReps:Math.min(maxReps,Math.max(minReps,reps+1)),reason:"La meilleure prochaine étape est une petite amélioration des répétitions à charge constante.",signals,effortZone,qualityScore};
}
export function getLiveSetDecision(state:LiveSetState):LiveSetDecision{const decision=getProgressionDecision({weight:state.weight,reps:state.reps,rir:state.rir,minReps:state.minReps,maxReps:state.maxReps,readiness:state.readiness,trendPercent:state.trendPercent,recentMisses:state.recentMisses,recentSessions:3,consecutiveHardSets:state.consecutiveHardSets,fatigueTrend:state.consecutiveHardSets&&state.consecutiveHardSets>=3?"rising":"stable"});const nextSetNumber=Math.min(state.plannedSets,state.setNumber+1);const shouldRest=state.setNumber<state.plannedSets||state.completedSets<state.plannedSets;const baseRestSeconds=Math.max(30,state.baseRestSeconds??120);return {...decision,nextSetNumber,shouldRest,suggestedRestSeconds:getSuggestedRestSeconds(state.rir,baseRestSeconds,state.readiness)};}
